config:
  install_tree: $spack/opt/spack
  template_dirs:
  - $spack/templates
  module_roots:
    tcl: $spack/share/spack/modules
    lmod: $spack/share/spack/lmod
  build_stage:
  - /home/balay/spack-temp/stage/
  source_cache: $spack/var/spack/cache
  misc_cache: ~/.spack/cache
  verify_ssl: true
  checksum: true
  dirty: false
